package com.eka.voice2rx_sdk.common.models

import androidx.annotation.Keep

@Keep
enum class VoiceError {
    MICROPHONE_PERMISSION_NOT_GRANTED,
    CREDENTIAL_NOT_VALID,
    UNKNOWN_ERROR,
    SUPPORTED_LANGUAGES_COUNT_EXCEEDED,
    SUPPORTED_OUTPUT_FORMATS_COUNT_EXCEEDED,
    LANGUAGE_LIST_CAN_NOT_BE_EMPTY,
    OUTPUT_FORMAT_LIST_CAN_NOT_BE_EMPTY,
}